import Head from "next/head";
import Activities from "@/components/Activities";

export default function Contact() {

    return (
        <>
            <Head>
                <title>Activiteiten</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="text-blue-900 flex flex-col items-center">
                <h1 className="text-4xl font-bold mb-5">Activiteiten</h1>
                <p className="text-lg mx-4 lg:mx-64 text-center ">
                    Draag steeds kleren die vuil mogen worden en doe indien je het
                    hebt altijd je uniform aan! Kijk ook
                    zeker naar het weerbericht en trek indien nodig je regenjas aan. Onze activiteiten gaan namelijk zo
                    veel mogelijk buiten door, tenzij in situaties van noodweer!
                </p>
                <Activities/>
            </main>
        </>
    )
}