import Head from "next/head";

export default function Contact() {

    return (
        <>
            <Head>
                <title>Bannen</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main className="text-blue-900 flex flex-col items-center">
                <h1 className="text-4xl font-bold mb-5">Bannen</h1>
                <p className="text-lg mx-4 lg:mx-64 text-center ">
                    Onze KSA is opgedeeld in bannen of leeftijdsgroepen. Elke zaterdag wordt er voor elke ban
                    afzonderlijk een activiteit georganiseerd. Klik op de pijltjes voor meer info over de leiding van de
                    bannen.
                </p>


            </main>
        </>
    )
}