import Head from 'next/head'
import Navbar from "@/components/Navbar";


export default function Home() {
    return (
        <>
            <Head>
                <title>KSA Frisse Heikracht Bree</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <main>
                <Navbar/>
                <div className="bg-blue-900">
                </div>
            </main>
        </>
    )
}
